# Generated by Django 3.1.2 on 2020-10-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidences',
            options={'verbose_name_plural': 'Incidences'},
        ),
    ]
