# Generated by Django 3.1.2 on 2020-10-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_counties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counties',
        ),
    ]
