# Generated by Django 3.1.2 on 2020-10-23 20:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_delete_counties'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidences',
            name='geometria',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326),
        ),
    ]
