# Generated by Django 3.1.2 on 2020-10-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_incidences_geometria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidences',
            old_name='geometria',
            new_name='geometry',
        ),
    ]
